# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 668)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.height = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.height.setMinimum(0.1)
        self.height.setMaximum(2500000.0)
        self.height.setSingleStep(0.01)
        self.height.setObjectName("height")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.height)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.calculate = QtWidgets.QPushButton(self.centralwidget)
        self.calculate.setObjectName("calculate")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.calculate)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setObjectName("result")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.result)
        self.weight = QtWidgets.QSpinBox(self.centralwidget)
        self.weight.setObjectName("weight")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.weight)
        self.horizontalLayout.addLayout(self.formLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "K&ouml;rpergr&ouml;&szlig;e in m:"))
        self.label_2.setText(_translate("MainWindow", "Gewicht in kg:"))
        self.calculate.setText(_translate("MainWindow", "BMI berechnen!"))
        self.label_3.setText(_translate("MainWindow", "Dein BMI ist: "))
        self.result.setText(_translate("MainWindow", "20"))
